apiVersion: v1
kind: Service
metadata:
  name: {{ include "jamf.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "jamf.name" . }}
    helm.sh/chart: {{ include "jamf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "jamf.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
